# Step 1: Build the Angular app
FROM node:18 AS build
WORKDIR /app

# Copy package files first to leverage caching
COPY package.json package-lock.json ./
RUN npm install

# Copy the rest of the app
COPY . .

# Build the app
RUN npm run build --configuration=production

# Step 2: Serve the Angular app using Nginx
FROM  nginx:stable AS production
COPY --from=build /app/dist/demo /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]


