FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
WORKDIR /app
EXPOSE 80

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY ["EcoTech.Shared/EcoTech.Shared.csproj", "EcoTech.Shared/"]
COPY ["EcoTech.Domain/EcoTech.Domain.csproj", "EcoTech.Domain/"]
COPY ["EcoTech.Application/EcoTech.Application.csproj", "EcoTech.Application/"]
COPY ["EcoTech.Infrastructure/EcoTech.Infrastructure.csproj", "EcoTech.Infrastructure/"]
COPY ["EcoTech.API/EcoTech.API.csproj", "EcoTech.API/"]

RUN dotnet restore "EcoTech.API/EcoTech.API.csproj"
COPY . .

WORKDIR "/src/EcoTech.API"
RUN dotnet build "EcoTech.API.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "EcoTech.API.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "EcoTech.API.dll"]