apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: echotech
spec:
  ingressClassName: nginx
  rules:
    - host: local.echotech.com
      http:
        paths:
        - path: /api
          pathType: Prefix
          backend:
            service:
              name: echotech-api-nodeport-service
              port: 
                number: 8080
        - path: /v2
          pathType: Prefix
          backend:
            service:
              name: web2
              port:
                number: 8080
